apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-one-ktdd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-one-ktdd
    app.kubernetes.io/part-of: build-secret-lookup-baat
  name: component-one-ktdd
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: component-one-ktdd
status:
  loadBalancer: {}
